name: Build
on:
    pull_request:
        types: [ opened, synchronize, reopened ]
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: 14
            -   run: npm run project:full-test
