name: Build
on:
    pull_request:
        types: [ opened, synchronize, reopened ]
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                name: Full Test
                with:
                    node-version: 12
            -   run: |
                    npm i
                    npm run ncc:build
                    npm run ncc:full-test
                    cd dist/netgrif-components-core
                    npm link
                    cd ../..
                    npm run nc:build
                    npm run nc:full-test
                    npm run example:build
