name: Publish package to GitHub Packages
on:
    release:
        types: [ published ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: 12
            -   run: |
                    npm ci
                    npm run ncc:build
                    npm run ncc:full-test
                    cd dist/netgrif-components-core
                    npm link
                    cd ../..
                    npm run nc:build
                    npm run nc:full-test
                    npm run example:build

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: 12
                    registry-url: https://registry.npmjs.org/
            -   run: npm ci
            -   run: npm run project:local-build
            -   run: npm publish --access public
                env:
                    NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: 12
                    registry-url: https://npm.pkg.github.com
            -   run: npm ci
            -   run: npm run project:local-build
            -   run: npm publish --access public
                env:
                    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
